"""empty message

Revision ID: 30f1f2e55422
Revises: d06e36eaedaa
Create Date: 2019-06-09 16:14:00.591763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30f1f2e55422'
down_revision = 'd06e36eaedaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('item', 'items')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('items', 'item')