"""empty message

Revision ID: d06e36eaedaa
Revises: 9c0b17799246
Create Date: 2019-06-09 16:08:33.173630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06e36eaedaa'
down_revision = '9c0b17799246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('item', 'items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('items', 'item')
    # ### end Alembic commands ###
